import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useEditorial } from '../components/Editorial';
import { editorClient } from '../lib/editor';
export default function Account(){
  const {session,member,ready,error}=useEditorial();
  const [email,setEmail]=useState(''),[token,setToken]=useState(''),[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[status,setStatus]=useState('');
  async function login(){if(!editorClient)return;setBusy(true);setStatus('');try{const result=sent?await editorClient.auth.verifyOtp({email:email.trim(),token:token.trim(),type:'email'}):await editorClient.auth.signInWithOtp({email:email.trim(),options:{shouldCreateUser:false,emailRedirectTo:window.location.origin+import.meta.env.BASE_URL+'account'}});if(result.error)throw result.error;setSent(true);setStatus(sent?'Signed in.':'Check your email for a sign-in link or code.');}catch(error){setStatus((error as Error).message);}finally{setBusy(false);}}
  return <div className="shell account-page"><span className="section-kicker">The owners’ entrance</span><h1>Owner account</h1>
    {!editorClient?<p>Owner sign-in is being set up. The public league archive remains available.</p>:!ready?<p>Checking your account…</p>:session?<><p>Signed in as {session.user.email}</p>{member?<><p>{member.role==='commissioner'?'Commissioner access · Use “Visual editor” above to edit outlined text, or open any owner profile.':'Your account is connected to your owner profile.'}</p>{member.owner_id&&<Link className="pill" to={`/owners/${member.owner_id}`}>Open my profile</Link>} {member.role==='commissioner'&&<Link className="pill" to="/owners">Browse owner profiles</Link>}</>:<p>Your email is verified, but it has not been assigned an owner profile. Ask the commissioner to connect your account.</p>}<p><button className="pill" disabled={busy} onClick={async()=>{setBusy(true);const {error}=await editorClient!.auth.signOut();if(error)setStatus(error.message);else{setSent(false);setToken('');}setBusy(false);}}>Sign out</button></p></>:<form onSubmit={e=>{e.preventDefault();void login();}}><p>Sign in with your registered email. This device remembers your login until you sign out or your session expires.</p><label>Email address<input type="email" autoComplete="email" required value={email} disabled={sent||busy} onChange={e=>setEmail(e.target.value)}/></label>{sent&&<label>Email code<input autoComplete="one-time-code" inputMode="numeric" required value={token} onChange={e=>setToken(e.target.value)}/></label>}<div className="editor-actions"><button className="pill" disabled={busy}>{busy?'Please wait…':sent?'Verify code':'Send sign-in email'}</button>{sent&&<button type="button" className="pill" disabled={busy} onClick={()=>{setSent(false);setToken('');setStatus('');}}>Use another email / resend</button>}</div></form>}
    <p role="status">{status||error}</p><p><Link to="/">Back to the league</Link></p>
  </div>;
}
